version: '2'
services:
  acewiki:
    build: .
    image: tkuhn/acewiki:attempto
    restart: unless-stopped
    volumes:
      - ./data:/opt/application/AceWiki/data
    ports:
      - 9077:9077
  owllinkapi:
    image: tkuhn/owllinkapi
    restart: unless-stopped
